### ISSUE TITLE
High Level Features Download

### ISSUE THREAD

**Issue by powerlego** [Earnings-Call-Dataset/MAEC-A-Multimodal-Aligned-Earnings-Conference-Call-Datasetfor-Financial-Risk-Prediction#2]
The download link for the high-level features no longer exists, is there an updated version of the high-level features

**Comment by lijiazheng99** [comment]
We don't have updated high-level features, just the original ones. Could you send me an email, please? Thanks

**Comment by powerlego** [comment]
I have just sent you an email, it should be coming from an rit.edu email

**Comment by zhaomin1995** [comment]
> I have just sent you an email, it should be coming from an rit.edu email

Hi,

Could you please share the high-level features with me? My email address is zhaominxiao@my.unt.edu

Best,
Zhaomin

**Comment by Ausen-Good** [comment]
> We don't have updated high-level features, just the original ones. Could you send me an email, please? Thanks

I want to have a copy of the high-level features to support my work, could you please sent share it with me? and i will sent you email.
