### ISSUE TITLE
Dataset download link

### ISSUE THREAD

**Issue by JamesChapmanNV** [Earnings-Call-Dataset/MAEC-A-Multimodal-Aligned-Earnings-Conference-Call-Datasetfor-Financial-Risk-Prediction#5]
Hello!
The link (https://drive.google.com/file/d/1yXLv1r5n35s4Nf7kvP96RSPLKyR-ZeUT/view?usp=sharing) on README.md, is not working.

**Comment by lijiazheng99** [comment]
Closing this issue since I have replied in email.
